baseurl = "/"
languageCode = "en-us"
title = "Scheuerell Lab"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Mark Scheuerell"
	description = "Applied Ecology Lab"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Scheuerell Lab"

		[params.navigation.links]
			about     = "About"
			team      = "People"
			services  = "Approach"
			portfolio = "Projects"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header-bg.jpg' at './static/img' with your own.
    slogan = "Scheuerell Lab"
    subtitle = ""
    buttonText = "Learn more"


	# About section
	[params.about]
		headline_1    = "MISSION"
		description_1 = "Using our knowledge and skills to help solve real-world problems."
		headline_2    = "VISION"
		description_2 = "Our vision is to better understand and manage aquatic ecosystems through the integration of data, analysis, and communication. Our team works in an open science environment, relying on trust and respect to build effective partnerships. We continually strive to expand upon and improve our complimentary skillsets through education and innovation, and we believe strongly in the sharing of knowledge through conversation and writing."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Our approach to science"

    [[params.services.list]]
      icon = "fa-flask"
      title = "Empirical data"
      description = "Hands-on field and lab studies."
      url = "https://github.com/scheuerell-lab"

    [[params.services.list]]
      icon = "fa-laptop"
      title = "Quantitative analyses"
      description = "Finding signals among the noise in data."
      url = "https://github.com/scheuerell-lab"

		[[params.services.list]]
      icon = "fa-comments-o"
      title = "Communication"
      description = "Sharing our information and listening to others."
      url = "https://twitter.com/mark_scheuerell"

    [[params.services.list]]
      icon = "fa-unlock"
      title = "Open science"
      description = "Creating accessible and reproducible workflows."
      url = "https://github.com/scheuerell-lab"

  # Team section
  [params.team]
    enable = true
    center = true
    title = "Our team"
    subtitle = ""
    description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "Mark.jpg"
      name = "Mark Scheuerell"
      position = "Principal Investigator"
      reportsTo = ""
      livesIn = ""
      scope = [
      #   "UX for [member dashboard](#)",
      #   "Maintainer for [awesome-project](#)",
      ]
      # For bio markdown and even multiline strings are available.
      bio = "Mark apparently leads this group, but he's always trying to catch up to everyone else. You can find out more about him [here](https://faculty.washington.edu/scheuerl/)."
      social = [
        ["fa-twitter", "https://twitter.com/mark_scheuerell"],
        ["fa-github", "https://github.com/mdscheuerell"],
      ]

    [[params.team.members]]
      img = "ashes.jpg"
      name = "Ashes Kittyball"
      position = "Sleepy Cat"
      reportsTo = ""
      livesIn = ""
      scope = [
      #   "UX for [member dashboard](#)",
      #   "Maintainer for [awesome-project](#)",
      ]
      # For bio markdown and even multiline strings are available.
      bio = "Ashes loves to avoid people and sleep while doing it."
      social = [
       ["fa-twitter", "https://twitter.com/search?q=%23CatsOfTwitter"]
      ]

    [[params.team.members]]
      img = "cassette.jpg"
      name = "Sam"
      position = "Future lab member"
      reportsTo = ""
      livesIn = ""
      scope = [
      #   "UX for [member dashboard](#)",
      #   "Maintainer for [awesome-project](#)",
      ]
      # For bio markdown and even multiline strings are available.
      bio = "Sam's not afraid to make mistakes and learn from them. Outside of academia, Sam enjoys competitive dog grooming, mountain unicycling, and gardening."
      social = [
       ["fa-twitter", "https://twitter.com/search?q=%23wellrounded"]
      ]

  # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

  # Aside section
	# [params.aside]
		# headline = ""

		# [params.aside.button]
			# text = ""
			# link = ""

	# Contact section
	[params.contact]
		headline = "Contact info"
		description = "School of Aquatic and Fishery Sciences<br>University of Washington<br>PO Box 355020<br>Seattle, WA 98195-5020"
		phone = ""
		email = "scheuerl@uw.edu"

	# Google Maps section
	[params.location]
	 	map = 1
	 	latitude  = "47.653311"
	 	longitude = "-122.316222"
	 	maps_api_key = "AIzaSyCOM_4Igg4AmZuG4Hv7KUqzSDvOiA8iu9A"

  # Footer section
  [params.footer]
    enable = true
    copyright = "&copy; 2019 Mark Scheuerell"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/mark_scheuerell"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/scheuerell-lab"
      title = "GitHub"

    [[params.footer.quicklinks]]
      text = "Based on the Hugo Creative Theme"
      link = "https://github.com/digitalcraftsman/hugo-creative-theme"
