baseurl = "https://depts.washington.edu/appliedecology/"
languageCode = "en-us"
title = "Scheuerell Lab"
theme = "hugo-creative-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]
disableKinds = ["taxonomy", "taxonomyTerm"]
googleAnalytics = ""
relativeurls = false

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Mark Scheuerell"
	description = "Applied Ecology Lab"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# ----------
	# Navigation
	# ----------
	[params.navigation]
		brand = "Applied Ecology Lab"

		[params.navigation.links]
			about     = "About"
			team      = "People"
			services  = "Research"
			prospectives = "Prospective Students"
			contact   = "Contact"


	# ------------
	# Hero section
	# ------------
	[params.hero]
		# To change the background of the hero section, replace 'header-bg.jpg' at './static/img'.
    slogan = "Applied Ecology Lab"
    subtitle = "Science supporting conservation & management"
    buttonText = "Learn more"


  # -------------
  # About section
  # -------------
  [params.about]
		headline_1    = "MISSION"
		description_1 = "Using our knowledge and skills to help solve real-world problems."
		headline_2    = "VISION"
		description_2 = "Our vision is to better understand and manage aquatic ecosystems through the integration of data, analysis, and communication."
		headline_3    = "VALUES"
		description_3 = "We are dedicated to providing a welcoming and supportive environment for all people, regardless of their background, identity, appearance, or manner of communication. Our team works in an open science environment, relying on trust and respect to build effective partnerships. We continually strive to improve and expand upon our complimentary skillsets through education and innovation, and we believe strongly in the sharing of knowledge through conversation and writing."
		headline_4    = "LAND ACKNOWLEDGMENT"
		description_4 = "We acknowledge the ancestral homelands of those who walked here before us and those who still walk here, keeping in mind the integrity of this territory where area Native peoples identify as the Duwamish, Suquamish, Snoqualmie, and Puyallup, as well as the tribes of the Muckleshoot, Tulalip, other Coast Salish peoples, and their descendants. We are grateful to respectfully live and work as guests on these lands with the Coast Salish and Native people who call this home."
		buttonText  = ""


  # ------------
  # Team section
  # ------------
  [params.team]
    enable = true
    center = true
    title = "OUR TEAM"
    description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.PI]]
      name = "Mark Scheuerell"
      position = "Principal Investigator"
      img = "Mark.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Mark's research interests lie at the intersection of ecology and management. He is broadly interested in the roles of natural and anthropogenic drivers on freshwater and coastal ecosystems, and the services we derive from them. You can find out more about Mark's research and teaching interests [**here**](https://faculty.washington.edu/scheuerl/). Mark also appreciates a healthy work-life balance. In his free time, Mark enjoys cycling, skiing, and spending time with his family."
      social = [
        ["fa-twitter", "https://twitter.com/mark_scheuerell"],
        ["fa-github", "https://github.com/mdscheuerell"]
      ]

    [[params.team.members]]
      name = "Dara Farrell"
      position = "Post-doc"
      img = "Dara.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Dara obtained her Ph.D. in  Mechanical Engineering from the University of Washington in Seattle in the summer of 2019 where the focus of her research was underwater acoustics – specifically anthropogenic and background noise characterization. Dara began her university career with a Bachelor’s degree in Chemical Engineering from the University of the West Indies in Trinidad & Tobago, and went on to complete her Masters degree in Environmental Engineering at the University of Illinois at Urbana Champaign on a Fulbright-LASPAU scholarship. She strives toward a multi-disciplinary approach to measuring, understanding and solving environmental problems, and uses machine learning, GIS and passive acoustics in her work. She finds great satisfaction in being involved in multi-disciplinary projects which allow her to hone her engineering- and acoustics-related skills."
      social = [
        ["fa-instagram", "https://www.instagram.com/mywondererslife/"],
        ["fa-github", "https://github.com/daramf"]
        ]
      
    [[params.team.members]]
      name = "Markus Min"
      position = "MS Student"
      img = "Markus.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Markus’s academic and research interests are primarily focused on the application of ecological and statistical models to the management of marine ecosystems and fisheries. Prior to coming to SAFS, he completed his BS in Marine Biology at UCLA and worked as a research assistant in the Biological Oceanography Group at the Monterey Bay Aquarium Research Institute (MBARI). While his research at both UCLA and MBARI was focused on the new, exciting field of environmental DNA (eDNA), it was his time spent studying groundfish as an intern at [**NOAA Fisheries**](https://www.fisheries.noaa.gov/about/northwest-fisheries-science-center) that inspired him to return to Seattle to study fisheries science and marine ecology at SAFS. In addition to his academic interests, Markus enjoys playing music, baking, fishing, hiking, and watching hockey (he also hopes to one day play, but he needs to learn how to skate first). Find out more about Markus [**here**](https://www.markusmin.com/)."
      social = [
        ["fa-twitter", "https://twitter.com/markusamin"],
        ["fa-github", "https://github.com/markusmin"]
        ]
      
    [[params.team.members]]
      name = "Karl Veggerby"
      position = "MS Student"
      img = "Karl_V.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Before joining SAFS, Karl worked at [**NOAA Fisheries**](https://www.fisheries.noaa.gov/about/northwest-fisheries-science-center) on a wide variety of research projects ranging from shellfish farms in Puget Sound, to the lower Columbia River, to high altitude salmon spawning grounds in the Salmon River Basin, Idaho. In particular, his work has focused on using stable isotopes to better understand food web dynamics, analyzing otoliths to estimate past somatic growth of juvenile fish, and more recently, examining the habitat function of Puget Sound shellfish farms using underwater video. Karl obtained a BS in environmental sciences from Western Washington University in 2014. In his free time Karl makes and sells fine furniture with his father in their woodshop, enjoys skiing and other outdoor activities, drinks and brews beer with his friends, and goes on walks to say hello to the cats in his neighborhood."
      social = [
        ["fa-instagram", "https://www.instagram.com/itsahardwoodlife"],
        ["fa-github", "https://github.com/kvegg"]
        ]
        
    [[params.team.members]]
      name = "Nicole Doran"
      position = "MS Student"
      img = "Nicole.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Nicole is interested in studying culturally important fishery species that have been impacted by environmental change. Her current thesis work involves studying the impacts of urbanization, climate change, and predation by introduced species on Kokanee salmon in Lake Sammamish. Nicole is passionate about increasing equity and inclusion in STEM through her involvement with the SAFS Equity and Inclusion Committee and organizations such as the American Indian Science and Engineering Society and Society for the Advancements of Chicanos/Hispanics and Native Americans in Science. Outside of work, Nicole enjoys reading, cooking, and playing video games. Feel free to reach out if you have questions about the lab, her research, or how to support DEI in STEM!"
      social = [
        ["fa-twitter", "https://twitter.com/NicoleDoran10"],
        ["fa-github", "https://github.com/scheuerell-lab"]
        ]
        
    [[params.team.members]]
      name = "Andrea Hennings"
      position = "MS Student"
      img = "Andrea.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Andrea is a biologist with the [**Washington Department of Fish and Wildlife**](https://wdfw.wa.gov/) (WDFW) Marine Fish Science Unit where she is the Unit’s remotely operated vehicle (ROV) program data manager, video annotation supervisor, and field coordinator, as well as an ROV pilot. In this position, her work supports long-term monitoring and population assessments of Salish Sea groundfish, principally rockfish and lingcod, in untrawlable habitats. Prior to WDFW, Andrea was support staff to the Snohomish County Marine Resources Committee (MRC) where she contributed to a range of projects, including the development of a derelict crabbing gear education and outreach program and the regional citizen science expansion of the NOAA Mussel Watch water quality program. When she’s not looking at fish on a computer, Andrea enjoys growing her own food, skiing, and sailing with her husband and rescue dog."
      social = [
        ["fa-twitter", "https://twitter.com/WDFW"],
        ["fa-github", "https://github.com/scheuerell-lab"]
        ]
        
    [[params.team.members]]
      name = "Sarah Hensley"
      position = "Undergraduate Student"
      img = "Sarah.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Sarah is currently a junior pursuing a degree in Marine Biology, and is particularly interested in better understanding the influence environmental change is having on our ecosystems and individual species through statistical analysis and research. She has spent some time interning with NOAA Fisheries in both the Northwest Fisheries Science Center and the Northeast Fisheries Science Center, which has inspired her to continue pursuing research in this field. Her projects involved looking at anthropogenic impacts on locally important species, ranging from sea lions to spiny dogfish. This year, Sarah is participating in the [**IBIS Research Program**](https://environment.uw.edu/students/current-students/identity-belonging-and-inquiry-in-science-ibis-program) where she will be working under the mentorship of Markus Min in our lab. Outside of academics, Sarah enjoys hiking, kayaking, and listening to music in the great outdoors, as well as painting."
      social = [
        ["fa-twitter", "https://twitter.com/UW_SAFS"],
        ["fa-github", "https://github.com/scheuerell-lab"]
        ]
        
    [[params.team.members]]
      name = "Olivia Anderson"
      position = "Undergraduate Student"
      img = "Olivia.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Olivia is currently a senior at UW majoring in marine biology. Her journey towards studying marine biology was deeply inspired by her upbringing in Kodiak, Alaska. It seems only natural that Kodiak’s vast, rich marine ecosystem would capture Olivia's interest and guide her towards a career involving marine biology. Over the years, Olivia's passion for marine life has fueled her desire to join a field that would allow her to preserve our oceans. Olivia looks forward to gaining hands-on research experience here in our lab."
      social = [
        ["fa-twitter", "https://twitter.com/UW_SAFS"],
        ["fa-github", "https://github.com/scheuerell-lab"]
        ]
        
    [[params.team.former]]
      people = [
        [" "],
        ["Kerrianne McCarthy (Undergraduate, 2019-2020)"],
        ["Kelly Mistry (MS Student,  2020-2022)", "fa-external-link", "https://www.kellyrmistry.com/"],
        ["Catherine Wangen (Research Scientist, 2022)", "fa-external-link", "https://github.com/cwangen"],
        ]

  # ---------------
  # Service section
  # ---------------
  [params.services]
    headline = "OUR RESEARCH"
    synopsis = "Research in the Applied Ecology Lab focuses on the conservation and management of aquatic resources, particularly within Washington State and along the west coast of North America. Much of our research is focused on the development and application of statistical methods for analyzing temporal and spatial data, but we collect our own data as well. Please see below for some examples of recent projects in our lab. <br><br> In particular, our research relies on a combination of empirical data, quantitative analysis, and communication. We also pursue our scientific endeavors in an open science environment where we create accessible and reproducible workflows."
    tenets = ""
      
    [[params.services.list]]
      icon = "fa-flask"
      title = "Empirical data"
      description = "Hands-on field and lab studies."
      url = "https://github.com/scheuerell-lab"
      
    [[params.services.list]]
      icon = "fa-laptop"
      title = "Quantitative analysis"
      description = "Finding signals among the noise in data."
      url = "https://github.com/scheuerell-lab"
      
    [[params.services.list]]
      icon = "fa-comments-o"
      title = "Communication"
      description = "Sharing our information and listening to others."
      url = "https://twitter.com/mark_scheuerell"
      
    [[params.services.list]]
      icon = "fa-unlock"
      title = "Open science"
      description = "Creating accessible and reproducible workflows."
      url = "https://github.com/scheuerell-lab"
      
  # ----------------
  # Portfolio modals
  # ----------------
  [params.portfolio.modal]
    client = "Collaborator(s)"
    date = "Date"
    category = "Category"
    buttonText = "Close"

  # ---------------
  # Contact section
  # ---------------
  [params.contact]
		headline = "Contact info"
		description = "School of Aquatic and Fishery Sciences, University of Washington, PO Box 355020, Seattle, WA 98195-5020"
		phone = ""
		email = "scheuerl@uw.edu"

	# -------------------
	# Google Maps section
	# -------------------
	[params.location]
	 	map = 1
	 	latitude  = "47.652639"
	 	longitude = "-122.316389"
	 	maps_api_key = ""

	# --------------
	# Footer section
	# --------------
	[params.footer]
    enable = true
    copyright = "&copy; 2022 Mark Scheuerell"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/mark_scheuerell"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/scheuerell-lab"
      title = "GitHub"

    [[params.footer.quicklinks]]
      text = "Adapted from the Hugo Creative Theme"
      link = "https://github.com/digitalcraftsman/hugo-creative-theme"

  # -------------
  # Aside section
  # -------------
  [params.aside]
    headline = ""
  
      [params.aside.button]
        text = ""
        link = ""

  # --------------------
  # Prospectives section
  # --------------------
  [params.prospectives]
		title = "PROSPECTIVE STUDENTS"
