baseurl = "https://depts.washington.edu/appliedecology/"
languageCode = "en-us"
title = "Scheuerell Lab"
theme = "hugo-creative-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]
disableKinds = ["taxonomy", "taxonomyTerm"]
googleAnalytics = ""
relativeurls = false

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Mark Scheuerell"
	description = "Applied Ecology Lab"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# ----------
	# Navigation
	# ----------
	[params.navigation]
		brand = "Applied Ecology Lab"

		[params.navigation.links]
			about     = "About"
			team      = "People"
			services  = "Research"
			prospectives = "Prospective Students"
			contact   = "Contact"


	# ------------
	# Hero section
	# ------------
	[params.hero]
		# To change the background of the hero section, replace 'header-bg.jpg' at './static/img'.
    slogan = "Applied Ecology Lab"
    subtitle = "Science supporting conservation & management"
    buttonText = "Learn more"


  # -------------
  # About section
  # -------------
  [params.about]
		headline_1    = "MISSION"
		description_1 = "Using our knowledge and skills to help solve real-world problems."
		headline_2    = "VISION"
		description_2 = "Our vision is to better understand and manage aquatic ecosystems through the integration of data, analysis, and communication."
		headline_3    = "VALUES"
		description_3 = "We are dedicated to providing a welcoming and supportive environment for all people, regardless of their background, identity, appearance, or manner of communication. Our team works in an open science environment, relying on trust and respect to build effective partnerships. We continually strive to improve and expand upon our complimentary skillsets through education and innovation, and we believe strongly in the sharing of knowledge through conversation and writing."
		headline_4    = "LAND ACKNOWLEDGMENT"
		description_4 = "We acknowledge the Coast Salish peoples of this land, the land which touches the shared waters of all tribes and bands within the Suquamish, Tulalip and Muckleshoot nations."
		buttonText  = ""


  # ------------
  # Team section
  # ------------
  [params.team]
    enable = true
    center = true
    title = "OUR TEAM"
    description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.PI]]
      name = "Mark Scheuerell"
      position = "Principal Investigator"
      img = "Mark.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Mark's research interests lie at the intersection of ecology and management. He is broadly interested in the roles of natural and anthropogenic drivers on freshwater and coastal ecosystems, and the services we derive from them. You can find out more about Mark's research and teaching interests [**here**](https://faculty.washington.edu/scheuerl/). Mark also appreciates a healthy work-life balance. In his free time, Mark enjoys cycling, skiing, and enjoying Seattle and the surrounding area with his family."
      social = [
        ["fa-twitter", "https://twitter.com/mark_scheuerell"],
        ["fa-github", "https://github.com/mdscheuerell"]
      ]

    [[params.team.members]]
      name = "Markus Min"
      position = "PhD Student"
      img = "Markus.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Markus’s research interests are primarily focused on the application of ecological and statistical models to the management of marine ecosystems and fisheries. In addition to his research, Markus is also passionate about mentoring, teaching, and advancing equity in science. Prior to coming to SAFS, he completed his BS in Marine Biology at UCLA and worked as a research assistant in the Biological Oceanography Group at the Monterey Bay Aquarium Research Institute (MBARI). While his research at both UCLA and MBARI was focused on the new, exciting field of environmental DNA (eDNA), it was his time spent studying groundfish as an intern at [**NOAA Fisheries**](https://www.fisheries.noaa.gov/) that inspired him to return to Seattle to study fisheries science and marine ecology at SAFS. In addition to his academic interests, Markus enjoys playing music, baking, fishing, hiking, and soccer. Find out more about Markus [**here**](https://www.markusmin.com/)."
      social = [
        ["fa-twitter", "https://twitter.com/markusamin"],
        ["fa-github", "https://github.com/markusmin"]
        ]
      
    [[params.team.members]]
      name = "Nicole Doran"
      position = "PhD Student"
      img = "Nicole.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Nicole is interested in studying culturally important fishery species that have been impacted by environmental change. Her Masters research explored frameworks of environmental justice, food justice, and community resilience that center Indigenous communities and their perspectives. Nicole's current dissertation work involves studying the impacts of urbanization, climate change, and predation by introduced species on Kokanee salmon in Lake Sammamish. Nicole is passionate about increasing equity and inclusion in STEM through her involvement with organizations such as the [**American Indian Science and Engineering Society**](https://www.aises.org/) and [**Society for the Advancements of Chicanos/Hispanics and Native Americans in Science**](https://www.sacnas.org/). Outside of work, Nicole enjoys reading, cooking, and playing video games. Feel free to reach out if you have questions about the lab, her research, or how to support DEI in STEM!"
      social = [
        ["fa-twitter", "https://twitter.com/SAFS"],
        ["fa-github", "https://github.com/NCDoran"]
        ]
        
    [[params.team.members]]
      name = "Brian McGreal"
      position = "PhD Student"
      img = "Brian.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Brian's academic interests focus on management of common pool resources. He graduated from the University of Arizona in December 2021 with a MS in Applied Econometrics and Policy Analysis from the Department of Agricultural and Resource Economics. He was the primary author of the University of Arizona Water Resources Research Center’s 2021 _Arroyo, Groundwater Management – Past, Present and Future_ and 2022 _Arroyo, Water Resilience – Indigenous Perspectives_. Brian is currently pursuing a PhD in [**Quantitative Ecology and Resource Management**](https://quantitative.uw.edu/graduate/qerm/), where he's receiving intensive training in the application of statistical, mathematical, and decision sciences to terrestrial and aquatic ecology, natural resource management, biometrics, and mathematical biology. Brian's research involves best management practices for salmon populations."
      social = [
        ["fa-twitter", "https://twitter.com/UW_SAFS"],
        ["fa-github", "https://github.com/themacfreezie"]
        ]
      
    [[params.team.members]]
      name = "Angela Dillon"
      position = "PhD Student"
      img = "mt-rainier-puyallup-river.jpeg"
      # For bio, markdown and multiline strings are possible.
      bio = "Angela was born and raised in the Puyallup Valley and is an enrolled member of the Puyallup Tribe. She has a BS Aquatic and Fisheries Sciences from UW and a MS from the Evergreen State College where she studied juvenile salmon diets, restoration, and invertebrate prey resources in the Puyallup River watershed. Angela spent a few years doing water quality work in WRIA 7 before going to work for the Puyallup Tribe’s Fisheries Department. As a field biologist, she monitors adult and juvenile salmon in WRIA 10 and as the SEPA Reviewer. Angela is currently the Water Quality Manager at the Puyallup Tribe’s Fisheries Department. In my free time, she volunteers for the Puyallup Tribe’s Sustainability Working Group and the City of Puyallup. Angela love puppies, detective novels, and the fall is her favorite time of the year. [Co-advised with Daniel Schindler]"
      social = [
        ["fa-twitter", "https://twitter.com/UW_SAFS"],
        ["fa-github", "https://github.com/scheuerell-lab"]
        ]
      
    [[params.team.members]]
      name = "Andrea Hennings"
      position = "MS Student"
      img = "Andrea.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Andrea is a biologist with the [**Washington Department of Fish and Wildlife**](https://wdfw.wa.gov/) (WDFW) Marine Fish Science Unit where she is the Unit’s remotely operated vehicle (ROV) program data manager, video annotation supervisor, and field coordinator, as well as an ROV pilot. In this position, her work supports long-term monitoring and population assessments of Salish Sea groundfish, principally rockfish and lingcod, in untrawlable habitats. Prior to WDFW, Andrea was support staff to the Snohomish County Marine Resources Committee (MRC) where she contributed to a range of projects, including the development of a derelict crabbing gear education and outreach program and the regional citizen science expansion of the NOAA Mussel Watch water quality program. When she’s not looking at fish on a computer, Andrea enjoys growing her own food, skiing, and sailing with her husband and rescue dog."
      social = [
        ["fa-twitter", "https://twitter.com/WDFW"],
        ["fa-github", "https://github.com/arhennings"]
        ]
        
    [[params.team.members]]
      name = "Tessa Code"
      position = "MS Student"
      img = "Tessa.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Tessa’s interests include predator-prey dynamics and studying anthropogenic influence on marine and freshwater species. Her current work focuses on the impact of artificial light levels on predation risk to juvenile salmon in Lake Washington, WA. Before joining SAFS, Tessa worked for the National Park Service in St Croix, USVI where she developed skills in hydro-acoustics, scuba-diving, and long-term saturation tagging projects. While working as a marine debris technician for the NOAA Pacific Islands Fisheries Science Center, she found a passion for cleaning up the ocean and minimizing anthropogenic effects on marine species. After moving back to Seattle, Tessa began working for the [**USGS Western Fisheries Research Center**](https://www.usgs.gov/centers/western-fisheries-research-center), where she remains a biological science technician. In her free time, Tessa enjoys kayaking on the Puget Sound, tending to her vegetable garden, and snuggling with her rescue pup, Jacque."
      social = [
        ["fa-twitter", "https://twitter.com/SAFS"],
        ["fa-github", "https://github.com/scheuerell-lab"]
        ]
        
    [[params.team.members]]
      name = "Amirah Casey"
      position = "MS Student"
      img = "Amirah.jpeg"
      # For bio, markdown and multiline strings are possible.
      bio = "Amirah graduated from Western Washington University with a BS in Marine and Coastal Science with a minor in Spanish. While at WWU, she took part in research on the effects of PCBs and PBDEs on zebrafish and surf smelt. During her four years as an undergraduate, she was a marine science education intern at foundry10, the first undergraduate to teach a lab section of organismal biology, a peer mentor for the Marine and Coastal Science program and worked on the education team at Blue Zoo aquarium.  In addition to her studies in SAFS, Amirah is a member of the [**Future Rivers**](https://futurerivers.uw.edu/) program. When she is not in the lab or doing schoolwork, Amirah enjoys going to the gym, exploring the city with friends, and watching her favorite TV shows."
      social = [
        ["fa brands fa-linkedin", "https://www.linkedin.com/in/amirah-casey-b77404a3/"],
        ["fa-github", "https://github.com/scheuerell-lab"]
        ]
        
    [[params.team.members]]
      name = "Callie Murakami"
      position = "Undergraduate"
      img = "Callie.jpg"
      # For bio, markdown and multiline strings are possible.
      bio = "Callie is a sophomore majoring in Aquatic & Fishery Sciences and planning to minor in Quantitative Science. She is exploring the fisheries field and has an interest in freshwater ecology and conservation. With a grant from [**Conservation, Research and Education Opportunities International**](https://creoi.org/), Callie is working with Markus and collaborators at WDFW to understand spatial and temporal patterns of marine debris in Puget Sound. Callie volunteered at the Issaquah Salmon Hatchery in the fall of 2023 to help with coho and Chinook spawning, and has been interested in getting more hands-on experience ever since. When she is not studying, Callie enjoys playing roller derby, sewing, drawing, playing video games, and spending time with her roommates."
      social = [
        ["fa-github", "https://github.com/scheuerell-lab"]
        ]
        
    [[params.team.former]]
      people = [
        [" "],
        ["Sarah Hensley", "(Undergraduate Scholar, 2023-2024)", "fa-external-link", "https://github.com/veggerk"],
        ["Karl Veggerby", "(Masters Student, 2021-2023)", "fa-external-link", "https://github.com/veggerk"],
        ["Andrea Martinez", "(Research Scientist, 2023)", "fa-external-link", "https://www.linkedin.com/in/andrea-martinez-mma-0a005a165/"],
        ["Olivia Anderson", "(Undergraduate Scholar, 2023)", "fa-external-link", "https://environment.uw.edu/students/current-students/identity-belonging-and-inquiry-in-science-ibis-program/"],
        ["Kelly Mistry", "(Masters Student,  2020-2022)", "fa-external-link", "https://www.kellyrmistry.com/"],
        ["Catherine Wangen", "(Research Scientist, 2022)", "fa-external-link", "https://www.linkedin.com/in/catherine-wangen/"]
        ]

  # ---------------
  # Service section
  # ---------------
  [params.services]
    headline = "OUR RESEARCH"
    synopsis = "Research in the Applied Ecology Lab focuses on the conservation and management of aquatic resources, particularly within Washington State and along the west coast of North America. Much of our research is focused on the development and application of statistical methods for analyzing temporal and spatial data, but we collect our own data as well. Please see below for some examples of recent projects in our lab. <br><br> In particular, our research relies on a combination of empirical data, quantitative analysis, and communication. We also pursue our scientific endeavors in an open science environment where we create accessible and reproducible workflows."
    tenets = ""
      
    [[params.services.list]]
      icon = "fa-flask"
      title = "Empirical data"
      description = "Hands-on field and lab studies."
      url = "https://github.com/scheuerell-lab"
      
    [[params.services.list]]
      icon = "fa-laptop"
      title = "Quantitative analysis"
      description = "Finding signals among the noise in data."
      url = "https://github.com/scheuerell-lab"
      
    [[params.services.list]]
      icon = "fa-comments-o"
      title = "Communication"
      description = "Sharing our information and listening to others."
      url = "https://twitter.com/mark_scheuerell"
      
    [[params.services.list]]
      icon = "fa-unlock"
      title = "Open science"
      description = "Creating accessible and reproducible workflows."
      url = "https://github.com/scheuerell-lab"
      
  # ----------------
  # Portfolio modals
  # ----------------
  [params.portfolio.modal]
    client = "Collaborator(s)"
    date = "Date"
    category = "Category"
    buttonText = "Close"

  # ---------------
  # Contact section
  # ---------------
  [params.contact]
		headline = "Contact info"
		school = "School of Aquatic and Fishery Sciences"
		univ = "University of Washington"
		box = "PO Box 355020"
		city = "Seattle, WA 98195"
		phone = ""
		email = "scheuerl@uw.edu"

	# -------------------
	# Google Maps section
	# -------------------
	[params.location]
	 	map = 1
	 	latitude  = "47.652639"
	 	longitude = "-122.316389"
	 	maps_api_key = ""

	# --------------
	# Footer section
	# --------------
	[params.footer]
    enable = true
    copyright = "&copy; 2024 Mark Scheuerell"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/mark_scheuerell"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/scheuerell-lab"
      title = "GitHub"

    [[params.footer.quicklinks]]
      text = "Adapted from the Hugo Creative Theme"
      link = "https://github.com/digitalcraftsman/hugo-creative-theme"

  # -------------
  # Aside section
  # -------------
  [params.aside]
    headline = ""
  
      [params.aside.button]
        text = ""
        link = ""

  # --------------------
  # Prospectives section
  # --------------------
  [params.prospectives]
		title = "PROSPECTIVE STUDENTS"
