---
title: ''
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PROSPECTIVE STUDENTS

Thanks for your interest in possibly joining the Scheuerell Lab. The information provided here is intended to give you an idea of the qualities I look for in graduate students, and my general expectations for students in my lab.

## Qualities

I'm looking for students who are interested in the intersection of applied ecology and management. Students in my lab are motivated, receptive to new ideas, and willing to help others. You should be willing to take a chance on occasion, potentially make a mistake, and learn from it. We try our best to cultivate an inviting and inclusive atmosphere, and everyone in the lab is expected to abide by a code of conduct. Students who contribute to our diversity of backgrounds, opinions, and approaches are especially welcome. I intend to train not just good scientists, but good citizens as well.

## Funding

### RA

### TA

### Fellowships

* [NSF Graduate Research Fellowship](https://www.nsfgrfp.org/)

* [Nancy Foster Fellowship](http://fosterscholars.noaa.gov/aboutnf.html)

* [Ford Foundation](http://sites.nationalacademies.org/pga/fordfellowships/index.htm)

* [NOAA Margaret A. Davidson Graduate Fellowship](https://coast.noaa.gov/nerrs/research/davidson-fellowship.html)

* [NMFS-Sea Grant Joint Fellowship Program in Population and Ecosystem Dynamics and Marine Resource Economics](https://seagrant.noaa.gov/NMFS-SG-Fellowship)



## Expectations

As a member of our lab, there will be times when you are called upon to assist one or more of our colleagues with their research.

## Still interested?

If all of this sounds great to you, please send me an email that includes the following information: (1) a description of your research interests, relevant experience, skills/abilities, and career goals; (2) a CV or resume with your GPA; and (3) an exmaple of your writing (e.g., publication, term paper). This is your opportunity to make a good first impression, so take the time to introduce yourself, your background, where you work or study, and what drew you to me. I will read through the materials you send me, and if I determine that we may indeed make a good fit, I will try my best to respond to you in a reasonable time, but please be patient. I may also ask to meet potential students in person, but unfortunately I do not have the time to meet with every prospective student.

[SAFS Graduate Program](https://fish.uw.edu/students/about-graduate-program/how-to-apply/)


